
DB_NAME_DEFAULT='scilab_cloud_17'
DB_USER_DEFAULT='root'
DB_PASS_DEFAULT='root'
DB_HOST_DEFAULT=''

DB_PORT_DEFAULT=''

DB_NAME_SCILAB='scilab'
DB_USER_SCILAB='root'
DB_PASS_SCILAB='root'
DB_HOST_SCILAB=''
DB_PORT_SCILAB=''
